baseurl: "/"
languageCode: "en-us"
title: "Nicola Mauri"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Contact
      url: "about/"
      weight: 3
    - name: Research
      url: "research/"
      weight: 2

params:
  font-family: "sans-serif"
  description: "Nicola's personal website"
  footer: "&copy; Nicola Mauri  2022 | [Linkedin](https://www.linkedin.com/in/nicola-mauri-53a9a24b/) | [Twitter](https://twitter.com/nm_zeno) | [RePEc](https://ideas.repec.org/f/pma3114.html)" 
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true

