baseurl: "/"
languageCode: "en-us"
title: "A minimal Hugo website"
theme: "hugo-xmin"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

menu:
  main:
    - name: Home
      url: ""
      weight: 1
    - name: Contact
      url: "about/"
      weight: 4
    - name: Research
      url: "research/"
      weight: 2
    - name: Miscellaneous
      url: "miscellaneous/"
      weight: 3


params:
  description: "A website built through Hugo and blogdown."
  footer: "&copy; Nicola Mauri  2021 | [Linkedin](https://www.linkedin.com/in/nicola-mauri-53a9a24b/) | [Twitter](https://twitter.com/nm_zeno) | [RePEc](https://ideas.repec.org/f/pma3114.html)" 
markup:
  highlight:
    codeFences: false
  goldmark:
    renderer:
      unsafe: true
